import { Logger } from "@mocha/shared";
import type { QMLBindingMap, ParsedQMLDocument, ParsedQMLNode } from "./qml-parser.js";

const logger = new Logger("TypeGenerator");

export interface GeneratedType {
  name: string;
  properties: GeneratedProperty[];
  signals: GeneratedSignal[];
  imports: string[];
}

export interface GeneratedProperty {
  name: string;
  type: string;
  optional: boolean;
  isBinding: boolean;
  defaultValue?: string;
}

export interface GeneratedSignal {
  name: string;
  parameters: { name: string; type: string }[];
}

export class TypeGenerator {
  generateFromQML(document: ParsedQMLDocument, componentName: string): string {
    const types = this._extractTypes(document.root);
    const lines: string[] = [];

    lines.push("// Auto-generated by Mocha Type Generator");
    lines.push("// Do not edit manually\n");

    lines.push('import { Signal, QProperty } from "@mocha/core";');
    lines.push('import type { QQuickItemBase } from "@mocha/qml/widget-types";\n');

    lines.push(`export interface ${componentName}QML {`);
    for (const type of types) {
      lines.push(`  ${type.name}: {`);
      for (const prop of type.properties) {
        const optional = prop.optional ? "?" : "";
        lines.push(`    ${prop.name}${optional}: ${prop.type};`);
      }
      for (const sig of type.signals) {
        const params = sig.parameters.map((p) => `${p.name}: ${p.type}`).join(", ");
        lines.push(`    readonly ${sig.name}: Signal<(${params}) => void>;`);
      }
      lines.push("  };");
    }
    lines.push("}\n");

    lines.push(`export interface ${componentName}Controller {`);
    for (const type of types) {
      for (const sig of type.signals) {
        lines.push(`  ${type.name}${sig.name.slice(2)}: () => void;`);
      }
    }
    lines.push("}\n");

    lines.push(`declare global {`);
    lines.push(`  namespace Mocha {`);
    lines.push(`    interface Components {`);
    lines.push(`      ${componentName}: ${componentName}QML;`);
    lines.push(`    }`);
    lines.push(`  }`);
    lines.push(`}\n`);

    return lines.join("\n");
  }

  generateDTSFromWidgets(widgets: Record<string, string>): string {
    const lines: string[] = [];
    lines.push("// Auto-generated QML widget types\n");

    lines.push('import { Signal } from "@mocha/core";\n');

    lines.push(`declare module "@mocha/qml/widget-types" {`);

    for (const [name, parent] of Object.entries(widgets)) {
      lines.push(`  export interface ${name} extends ${parent} {`);
      lines.push(`    // Generated properties`);
      lines.push(`  }\n`);
    }

    lines.push("}");

    return lines.join("\n");
  }

  generateProjectTypes(
    components: Array<{ name: string; document: ParsedQMLDocument }>
  ): string {
    const lines: string[] = [];
    lines.push("// Project-specific type definitions");
    lines.push("// Generated by: mocha type-gen\n");

    for (const comp of components) {
      lines.push(this.generateFromQML(comp.document, comp.name));
    }

    return lines.join("\n\n");
  }

  private _extractTypes(
    node: ParsedQMLNode
  ): Array<{
    name: string;
    properties: GeneratedProperty[];
    signals: GeneratedSignal[];
  }> {
    const result: Array<{
      name: string;
      properties: GeneratedProperty[];
      signals: GeneratedSignal[];
    }> = [];

    const typeName = node.id ?? node.type;
    const properties: GeneratedProperty[] = [];
    const signals: GeneratedSignal[] = [];

    for (const [name, value] of Object.entries(node.properties)) {
      properties.push({
        name,
        type: this._inferType(value),
        optional: true,
        isBinding: typeof value === "object" && value?.type === "binding",
      });
    }

    for (const [name, handler] of Object.entries(node.signalHandlers)) {
      signals.push({
        name,
        parameters: [{ name: "value", type: "any" }],
      });
    }

    result.push({ name: typeName, properties, signals });

    for (const child of node.children) {
      result.push(...this._extractTypes(child));
    }

    return result;
  }

  private _inferType(value: unknown): string {
    if (value === null || value === undefined) return "any";
    if (typeof value === "boolean") return "boolean";
    if (typeof value === "number") return "number";
    if (typeof value === "string") {
      if ((value as string).startsWith("#")) return "string";
      if ((value as string).match(/^-?\d+px$/)) return "number";
      return "string";
    }
    if (typeof value === "object" && (value as any)?.type === "binding") {
      return "QProperty<any>";
    }
    return "any";
  }
}
